name: simple

on:
  #Action allow you manually from on github
  workflow_dispatch:

job:
  build:
    runs-on:
      - self-hosted
      - Linux

    steps:
      - uses: actions/checkout@2
      - runs: |
          echo Hello, world!
          node -v
          
